# Sample SpecTcl main program for testing GUI

use Tk;
require Tk::Menu;
my($top) = MainWindow->new();
$top->title("hello test");


# interface generated by SpecTcl (Perl enabled) version 1.1 
# from hello.ui
# For use with Tk402.002, using the grid geometry manager

sub hello_ui {
	my($root) = @_;

	# widget creation 

	my($button_1) = $root->Button (
		-text => 'Hello world!',
	);

	# widget commands

	$button_1->configure(
		-command => sub{exit}
	);

	# Geometry management

	$button_1->grid(
		-in => $root,
		-column => '1',
		-row => '1'
	);

	# Resize behavior management

	# container $root (rows)
	$root->gridRowconfigure(1, -weight  => 0, -minsize  => 30);

	# container $root (columns)
	$root->gridColumnconfigure(1, -weight => 0, -minsize => 30);

	# additional interface code

	# end additional interface code
}
hello_ui $top;
Tk::MainLoop;

1;
